### PR TITLE
Relax FROM specificity to avoid unnecessary bumps every time ruby does

### PR DESCRIPTION
**Pull request by tianon**
```console
$ ./update.sh
+ curl -sSL https://raw.githubusercontent.com/docker-library/ruby/master/2.2/onbuild/Dockerfile -o onbuild/Dockerfile
+ echo
+ grep '^RUN.*apt-get install' Dockerfile
+ echo
+ echo 'EXPOSE 3000'
+ echo 'CMD ["rails", "server", "-b", "0.0.0.0"]'
+ sed -ri 's/^(FROM ruby):.*/\1:2.2/' onbuild/Dockerfile
++ grep -m1 '^FROM' onbuild/Dockerfile
+ sed -ri '
	s/^FROM .*/FROM ruby:2.2/;
	s/^(ENV RAILS_VERSION) .*/\1 4.2.1/;
' Dockerfile
```

### CODE REVIEW

**Comment by yosifkit** [comment]
LGTM

**Comment by md5** [comment]
Are you guys planning to manually bump the downstream images when the `ruby` update is security-related?

**Comment by tianon** [comment]
Yeah, we do that already. :+1:

**Comment by md5** [comment]
Right. I suppose that the `ruby:X.Y` tag would be updated in that case.

**Comment by tianon** [comment]
Yep!

**Pull request merged**
